### ISSUE TITLE
does not handle Binary files

### ISSUE THREAD

**Issue by Nicolas-Masson-Wizaplace** [ofw/curlify#19]
I made a fix to make it works with posting CSV files, but have no success with Jpeg file.

**Comment by ofw** [comment]
Ok, I'll look into it

**Comment by leNEKO** [comment]
2 PR that would fix this :)
https://github.com/ofw/curlify/pull/22
https://github.com/ofw/curlify/pull/23

**Comment by ornichola** [comment]
@leNEKO @ofw is it possible to merge this PRs?

**Comment by DennyWeinberg** [comment]
I have the same issue.

Body:
`n'x\x9c\x95Skk\xe2@\x...`

Error:
`      File "/opt/ls/lx/release/d_dwe_lxstacon/local/ux_app/python/lib/python3.6/site-packages/curlify.py", line 28, in to_curl     body = body.decode('utf-8')     UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte`

**Comment by fenchu** [comment]
I have the same problem when working with OCSP it uses a binary ASN.1 format:
https://www.e2encrypted.com/pki/pki-certificate-revoke-ocsp/



OCSP have specific content-type and accept and binary payload and return a binary payload
```
    session.headers.update(
        {'Content-type': 'application/ocsp-request', 'Accept': 'application/ocsp-response'}
    )

20250527140304.946|INFO|C:\dist\ca-ocsp-tests\tools\ocsp.py:417|ocsp response received from http://ocsp.test4.buypass.no/ocsp/BPClass2T4CA3, length: 508 bytes
Traceback (most recent call last):
  File "C:\dist\ca-ocsp-tests\get_certs.py", line 528, in <module>
    res = tools.ocsp.postreq(ocspurl, req, debug=args.debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dist\ca-ocsp-tests\tools\ocsp.py", line 418, in postreq
    log.info(curlify.to_curl(r.request))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dist\venvs\ca-ocsp-tests\Lib\site-packages\curlify.py", line 28, in to_curl
    body = body.decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^
```

**Comment by fenchu** [comment]
Made a simple patch that handle binary bodies, it uses `--data-binary @<uuid>.burlbinbody`. it leaves a file in root, so it may not be elegant, But in my case I need to be able to rerun those openssl posts with curl.

[curlify.patch](https://github.com/user-attachments/files/20628611/curlify.patch)

example:

```
        r = session.post(ocspurl, data=data, timeout=10.0)
        r.raise_for_status()
        if r and hasattr(r, 'content'):
            resp = r.content
            log.info(f"ocsp response received from {ocspurl}, length: {len(resp)} bytes")
            log.info(curlify.to_curl(r.request))
```
output:
```
ocsp response received from http://ocspps.test4.buypassca.com, length: 1850 bytes
curl.exe -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: application/ocsp-response' -H 'Connection: keep-alive' -H 'Content-type: application/ocsp-request' -H 'Content-Length: 78' --data-binary @41ba4a68-42d8-11f0-b4f8-00933765fb8e.curlbinbody http://ocspps.test4.buypassca.com/

```

running the curl:
```
curl.exe -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: application/ocsp-response' -H 'Connection: keep-alive' -H 'Content-type: application/ocsp-request' -H 'Content-Length: 78' --data-binary @41ba4a68-42d8-11f0-b4f8-00933765fb8e.curlbinbody http://ocspps.test4.buypassca.com/
Warning: Binary output can mess up your terminal. Use "--output -" to tell curl to output it to your terminal anyway, or consider "--output <FILE>" to save to a file.

curl.exe -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: application/ocsp-response' -H 'Connection: keep-alive' -H 'Content-type: application/ocsp-request' -H 'Content-Length: 78' --data-binary @41ba4a68-42d8-11f0-b4f8-00933765fb8e.curlbinbody http://ocspps.test4.buypassca.com/ --output ocspresp.der
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1928  100  1850  100    78  33882   1428 --:--:-- --:--:-- --:--:-- 37076


# You see the ocsp reps is valid (although the domain is not verified)
& 'C:\Program Files\OpenSSL-Win64\bin\openssl.exe' ocsp -respin .\ocspresp.der -text | Select -First 5 
OCSP Response Data:Response Verify Failure
A4570000:error:13800065:OCSP routines:ocsp_verify_signer:certificate verify error:crypto\ocsp\ocsp_vfy.c:64:Verify error: unable to get local issuer certificate

    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = NO, O = Buypass AS, CN = Buypass Test4 OCSP PS, organizationIdentifier = NTRNO-983163327
```
